In [12]:
name = "Arewa Data Science Academy"
year = 2026
print(f"Hello from {name}, {year}")

Hello from Arewa Data Science Academy, 2026

## First notebook — getting used to cells

In [13]:
import pandas as pd

data = {
    "student": ["Amina", "Kofi", "Tunde", "Zainab"],
    "score": [88, 76, 95, 82],
}
df = pd.DataFrame(data)
df

  student  score
0   Amina     88
1    Kofi     76
2   Tunde     95
3  Zainab     82

In [14]:
df["passed"] = df["score"] >= 80
df

  student  score  passed
0   Amina     88    True
1    Kofi     76   False
2   Tunde     95    True
3  Zainab     82    True

In [2]:
# import pandas as pd

In [1]:
# import matplotlib.pyplot as plt

In [10]:
"code --install-extension GitHub.copilot"

"code --install-extension GitHub.copilot-chat"

'code --install-extension GitHub.copilot-chat'